// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/yangxuan/Desktop/onelight-study/ol-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@swc+helpers@0.5.1_@types+node@22.13.4_@types+react@19.0.10_es_hsyyju3nqwtarrwkegtcdsp7kq/node_modules/dumi/theme-default/builtins/CodeGroup/index.js';
