// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"DemoLayout":{"id":"DemoLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"DemoLayout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/yangxuan/Desktop/onelight-study/ol-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@swc+helpers@0.5.1_@types+node@22.13.4_@types+react@19.0.10_es_hsyyju3nqwtarrwkegtcdsp7kq/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/yangxuan/Desktop/onelight-study/ol-ui/apps/website/.dumi/tmp/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-lobehub__dist__layouts__DocLayout__index" */'/Users/yangxuan/Desktop/onelight-study/ol-ui/apps/website/node_modules/dumi-theme-lobehub/dist/layouts/DocLayout/index.js')),
'DemoLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi-theme-lobehub__dist__layouts__DemoLayout__index" */'/Users/yangxuan/Desktop/onelight-study/ol-ui/apps/website/node_modules/dumi-theme-lobehub/dist/layouts/DemoLayout/index.js')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/yangxuan/Desktop/onelight-study/ol-ui/apps/website/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/yangxuan/Desktop/onelight-study/ol-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@swc+helpers@0.5.1_@types+node@22.13.4_@types+react@19.0.10_es_hsyyju3nqwtarrwkegtcdsp7kq/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
