// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from '/Users/yangxuan/Desktop/onelight-study/ol-ui/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from '/Users/yangxuan/Desktop/onelight-study/ol-ui/node_modules/.pnpm/dumi@2.4.18_@babel+core@7.26.9_@swc+helpers@0.5.1_@types+node@22.13.4_@types+react@19.0.10_es_hsyyju3nqwtarrwkegtcdsp7kq/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
