// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/yangxuan/Desktop/onelight-study/ol-ui/apps/website/node_modules/dumi-theme-lobehub/dist/slots/Navbar/index.js';
